### ISSUE TITLE
Node parameters not being editable on left click

### ISSUE THREAD

**Issue by NotArme** [RodZill4/material-maker#772]
**Material Maker version:**
1.4a2

**OS/device including version:**
Windows 11

**Issue description:**
In some occasions, clicking on an editable line in a node will not show a caret, and not allow for text inputs

![Image](https://github.com/user-attachments/assets/a972b218-720b-49af-8a9b-22876d4193e5)

**Steps to reproduce:**
The bug will always occur if the mouse moves at least one pixel in any direction while clicking on the field, but seems to also happens randomly sometimes

**Comment by floetenmaul** [comment]
Yeah, this does make the usage somewhat tedious. It it easily reproducible, if you click on a float value, type in a value, accept it (either by clicking somewhere else node or press enter) and then click on that value again.

Also i would find it more comfortable if i could enter another value after pressing enter (without having to activate the field again). Cheers

p.s. beyond that, i really like the tool an am excited to see how it will develop in the future

**Comment by williamchange** [comment]
https://github.com/RodZill4/material-maker/pull/789 was merged so it should fix this

**Comment by NotArme** [comment]
> [#789](https://github.com/RodZill4/material-maker/pull/789) was merged so it should fix this

I just checked, at least this PR made it impossible for the bug to happen when the field is selected while the mouse is completely still, which should be most cases, and already makes it a lot better. however, due to simply checking the cursors' relative length, it still persists in some circumstances.
ie. moving the mouse vertically while clicking will still enter edit mode, but won't allow for keyboard inputs

https://github.com/user-attachments/assets/1c22c6a7-5e94-48df-a143-42ebbe01fdc1

In the video, i move the mouse a lot vertically to try and show exactly what's happening, but it even happens if even a single pixel is moved while clicking, which can happen somewhat often on normal use.

To fix the issue completely we would probably have to either find out the root problem of the caret not showing up (seems to be an issue with godot itself) or refactor the whole thing.

Although the PR did help, i'd think it's best to leave the issue open until we fix the bug completely
